### ISSUE TITLE
[Question] Tensorboard Logging Not Tracking All Values?

### ISSUE THREAD

**Issue by James-R-Han** [DLR-RM/stable-baselines3#1163]
### ❓ Question

I'm currently logging extra values in Tensorboard, using the following in a callback function:
```
class CustomCallback(BaseCallback):
    def __init__(self, verbose=0):
        super(CustomCallback, self).__init__(verbose)
       
    def _on_step(self) -> bool:
        # extra tensorboard logging
        for key, value in self.locals["infos"][0]["info"].items():
            self.logger.record(key, value.val)

            if key == "Collision" and value.val!=0:
                print(key, value.val)
```
Indeed the "Collision" key has a value.val that's not 0 some times:
![image](https://user-images.githubusercontent.com/50814323/200993590-c4ce7da5-f782-41e2-b73d-c11c2674595f.png)

But in Tensorboard it is all 0s:
![image](https://user-images.githubusercontent.com/50814323/200993667-75ef8c05-c204-497c-90ec-6272af83761f.png)

Would anyone happen to know why this is occurring? I do see values in my "Progress" reward logging properly, which I do nearly identically.

![image](https://user-images.githubusercontent.com/50814323/200993753-4f6556d8-18b7-4e31-896f-873ed12a1983.png)

Thanks in advance!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Yes it does, but you can't see it because tensorboard makes a kind of average to make the curves smoother. Look at what this example gives:


```python
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3 import PPO
import random


class CustomCallback(BaseCallback):
    def _on_step(self) -> bool:
        value = 0 if random.random() < 0.50 else 1
        self.logger.record("my_val", value)


PPO("MlpPolicy", "Pendulum-v1", tensorboard_log="./tensorboard/", verbose=1).learn(100_000, callback=CustomCallback())
```
![Screenshot from 2022-11-10 14-18-16](https://user-images.githubusercontent.com/45557362/201102460-11d69f49-bfff-49f1-93ed-80a8bb3205a2.png)

I would suggest to instead log the collision rate, instead of logging -80 when a collision occurs.

**Comment by James-R-Han** [comment]
Hey Quentin! Thanks for the response.

I know tensorboard does smoothing, but even when I turn it to 0, there's nothing displayed.

![image](https://user-images.githubusercontent.com/50814323/201115745-1562fbed-153a-40ac-b9e0-fcc7b4afddcf.png)

**Comment by qgallouedec** [comment]
In fact, you are right, the values are only sent to the tensorboard at the end of each rollout. So this is not about smoothing.

https://github.com/DLR-RM/stable-baselines3/blob/7e1db1aaaa0f486cceb79faf5a08a25c5fded670/stable_baselines3/common/on_policy_algorithm.py#L257-L267

However, I maintain my suggestion, it is more interesting to log a sliding average than a specific value for each interraction.

**Comment by James-R-Han** [comment]
Ah, thanks for finding that.

But, I'm less concerned about the display in the terminal and more about tensorboard. I'm calling self.logger.record(.) myself on every step in the callback for each reward type and it seems like only some of these reward types are consistently working and some are failing. Maybe there are some nuances with logger.record(.) I'm not familiar with?

Thanks again! Will be implementing the sliding average in the meantime

**Comment by James-R-Han** [comment]
Gotcha, thank you for the info Quentin! 

I also found this to call dump every timestep so I'm logging everything now: https://github.com/DLR-RM/stable-baselines3/issues/506
